version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16.13.0

    steps:
      - checkout
      - run: npm i --silent
      - run: npm test
      - run: npm run build

  production:
    docker:
      - image: circleci/node:16.13.0

    steps:
      - checkout
      - run: chmod +x deploy.sh
      - run: ./deploy.sh

workflows:
  test:
    jobs:
      - test
      - production:
          requires:
            - test
          filters:
            branches:
              only:
                - main
